export const DEFAULT_STATIONS = [
  { id: 'prep',     name: 'Сборка пиццы',      emoji: '🍕', parallelSlots: 6 },
  { id: 'oven',     name: 'Выпекание',          emoji: '🔥', parallelSlots: 2 },
  { id: 'fryer',    name: 'Фритюр',             emoji: '🍟', parallelSlots: 2 },
  { id: 'grill',    name: 'Гриль',              emoji: '🥩', parallelSlots: 2 },
  { id: 'stove',    name: 'Плита',              emoji: '🍲', parallelSlots: 4 },
  { id: 'assembly', name: 'Сборка и упаковка',  emoji: '📦', parallelSlots: 4 },
];

export const DEFAULT_EQUIPMENT = [
  {
    id: 'eq-ovens',
    type: 'oven',
    name: 'Печи для пиццы',
    emoji: '🔥',
    count: 6,
    capacityPerUnit: 4,
    station: 'oven',
    linkedDishes: ['margherita', 'pepperoni', 'calzone', 'bruschetta'],
  },
  {
    id: 'eq-fryers',
    type: 'fryer',
    name: 'Фритюры',
    emoji: '🍟',
    count: 2,
    capacityGrams: 3000,
    portionGrams: 300,
    station: 'fryer',
    linkedDishes: ['fries', 'nuggets'],
  },
];

export const DEFAULT_DISHES = [
  { id: 'margherita', name: 'Маргарита', emoji: '🍕', price: 350,
    station: 'prep', prepTimeSec: 25,
    bakingStation: 'oven', bakingTimeSec: 180,
    assemblyStation: 'assembly', assemblyTimeSec: 15,
    ingredients: 'тесто, соус томатный, моцарелла, базилик' },
  { id: 'pepperoni', name: 'Пепперони', emoji: '🍕', price: 420,
    station: 'prep', prepTimeSec: 35,
    bakingStation: 'oven', bakingTimeSec: 200,
    assemblyStation: 'assembly', assemblyTimeSec: 15,
    ingredients: 'тесто, соус томатный, моцарелла, пепперони' },
  { id: 'calzone', name: 'Кавабанга (закрытая)', emoji: '🍕', price: 550,
    station: 'prep', prepTimeSec: 90,
    bakingStation: 'oven', bakingTimeSec: 240,
    assemblyStation: 'assembly', assemblyTimeSec: 20,
    ingredients: 'тесто, много начинки, помидоры, грибы, курица' },
  { id: 'caesar', name: 'Салат Цезарь', emoji: '🥗', price: 320,
    station: 'prep', prepTimeSec: 40,
    bakingStation: '', bakingTimeSec: 0,
    assemblyStation: 'assembly', assemblyTimeSec: 10,
    ingredients: 'романо, курица гриль, пармезан, сухарики, соус цезарь' },
  { id: 'borsch', name: 'Борщ', emoji: '🍲', price: 280,
    station: 'stove', prepTimeSec: 55,
    bakingStation: '', bakingTimeSec: 0,
    assemblyStation: '', assemblyTimeSec: 0,
    ingredients: 'бульон, свёкла, капуста, картофель, морковь, сметана' },
  { id: 'steak', name: 'Стейк Рибай', emoji: '🥩', price: 890,
    station: 'grill', prepTimeSec: 120,
    bakingStation: '', bakingTimeSec: 0,
    assemblyStation: 'assembly', assemblyTimeSec: 15,
    ingredients: 'мраморная говядина, соль, перец, масло, тимьян' },
  { id: 'fries', name: 'Картошка фри', emoji: '🍟', price: 150,
    station: 'fryer', prepTimeSec: 20,
    bakingStation: '', bakingTimeSec: 0,
    assemblyStation: '', assemblyTimeSec: 0,
    ingredients: 'картофель, масло, соль' },
  { id: 'nuggets', name: 'Наггетсы', emoji: '🍗', price: 250,
    station: 'fryer', prepTimeSec: 25,
    bakingStation: '', bakingTimeSec: 0,
    assemblyStation: 'assembly', assemblyTimeSec: 10,
    ingredients: 'куриное филе, панировка, специи' },
  { id: 'soup', name: 'Суп дня', emoji: '🍜', price: 250,
    station: 'stove', prepTimeSec: 45,
    bakingStation: '', bakingTimeSec: 0,
    assemblyStation: '', assemblyTimeSec: 0,
    ingredients: 'бульон, овощи, зелень, сметана' },
  { id: 'bruschetta', name: 'Брускетта', emoji: '🍞', price: 280,
    station: 'oven', prepTimeSec: 30,
    bakingStation: '', bakingTimeSec: 0,
    assemblyStation: 'assembly', assemblyTimeSec: 10,
    ingredients: 'чиабатта, помидоры, базилик, чеснок, оливковое масло' },
];

export const DEFAULT_COMBOS = [
  { id: 'combo-pizza-9', name: 'Набор из 9 пицц', price: 3500, items: [
    { dishId: 'margherita', qty: 3 },
    { dishId: 'pepperoni', qty: 3 },
    { dishId: 'calzone', qty: 3 },
  ]},
  { id: 'combo-business-lunch', name: 'Бизнес-ланч ×5', price: 3900, items: [
    { dishId: 'borsch', qty: 5 },
    { dishId: 'caesar', qty: 5 },
    { dishId: 'bruschetta', qty: 5 },
  ]},
];

export const DEFAULT_COOKS = [
  { id: 'cook-1', name: 'Алексей',  emoji: '👨‍🍳', stations: ['prep', 'oven', 'grill'], speed: 1.0, dishTimes: {} },
  { id: 'cook-2', name: 'Мария',    emoji: '👩‍🍳', stations: ['stove', 'fryer', 'assembly'], speed: 1.0, dishTimes: {} },
  { id: 'cook-3', name: 'Дмитрий',  emoji: '👨‍🍳', stations: ['oven', 'stove', 'assembly'], speed: 0.9, dishTimes: {} },
];
